name: epgzonghe

# 每小时执行一次
on:
  schedule:
    - cron: '31 */2 * * *'  # 每小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境运行

    steps:
      # 第一步：检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 第二步：设置 PHP 7.4 环境
      - name: Set up PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      # 第三步：运行 epgziyong.php，生成 epgziyong.xml
      - name: Run epgziyong.php
        run: |
          php epgziyong.php  # 运行生成 epgziyong.xml 的 PHP 脚本


          # 将文件名列表写入 GITHUB_ENV，供后续步骤使用
          cat files.json | jq -r 'keys[]' | while read -r filename; do
            echo "FILENAME_$filename=$filename" >> $GITHUB_ENV
          done

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          files_to_add=""
          for var in $(env | grep 'FILENAME_' | cut -d '=' -f 2); do
            if [ -f "$var" ]; then
              files_to_add="$files_to_add $var"
            fi
          done
          
          if [ -n "$files_to_add" ]; then
            git add $files_to_add
            now_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
            git commit -m "更新时间：$now_time"
            git push origin main || echo "推送到GitHub失败"
          else
            echo "没有文件可提交"
          fi
