name: epgziyong

on:
  schedule:
    - cron: '11 */2 * * *'  # 每小時的第 1 分鐘執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest  # 使用 Ubuntu 環境運行

    steps:
      # 1. 檢出代碼
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整提交歷史，避免 Git 提交問題

      # 2. 設置 PHP 7.4 環境
      - name: Set up PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      # 3. 生成 epgkai.xml
      - name: Run epgziyong.php
        run: |
          php epgziyong.php

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          files_to_add=""
          for var in $(env | grep 'FILENAME_' | cut -d '=' -f 2); do
            if [ -f "$var" ]; then
              files_to_add="$files_to_add $var"
            fi
          done
          
          if [ -n "$files_to_add" ]; then
            git add $files_to_add
            now_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
            git commit -m "更新时间：$now_time"
            git push origin main || echo "推送到GitHub失败"
          else
            echo "没有文件可提交"
          fi          
          # 提交更新并添加时间戳
          now_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
          git commit -m "更新時間：$now_time"
          
          # 推送更新并处理可能的错误
          if ! git push origin main; then
            echo "推送到 tvepg 失敗"
            exit 1
          fi
